{
    "name": "IT Infrastructure",
    "version": "14.0.1.0.0",
    "author": "Lisandro Gallo",
    "license": "AGPL-3",
    "depends": ["mail"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/software_category_data.xml",
        "data/equipment_track_data.xml",
        "data/software_data.xml",
        "views/it_infra_menus.xml",
        "views/device_views.xml",
        "views/device_menus.xml",
        "views/device_category_views.xml",
        "views/device_category_menus.xml",
        "views/server_views.xml",
        "views/server_menus.xml",
        "views/server_category_views.xml",
        "views/server_category_menus.xml",
        "views/software_views.xml",
        "views/software_menus.xml",
        "views/software_category_views.xml",
        "views/software_category_menus.xml",
        "views/supply_views.xml",
        "views/supply_menus.xml",
        "views/supply_category_views.xml",
        "views/supply_category_menus.xml",
        "views/workstation_views.xml",
        "views/workstation_menus.xml",
        "views/location_views.xml",
        "views/location_menus.xml",
        "views/network_device_views.xml",
        "views/network_device_menus.xml",
        "views/network_device_port_views.xml",
        "views/provider_views.xml",
        "views/provider_menus.xml",
    ],
    "installable": True,
    "auto_install": False,
    "demo": [],
}  # yapf: disable
